name: infinite_scroll_view
description: Infinite Scroll View
version: 0.0.4
homepage: https://github.com/Jerinji2016/infinite_scroll_view

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
