name: Check Flutter Format and Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    # branches: [ develop, master ]
    branches: [ feature_ci_cd ]
    paths:
      - '**'
  # pull_request:
  #   branches: [ develop ]
  #   paths:
  #     - '**'

env:
  flutter_version: '3.7.12'
  # java_version: 11

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  format:
    name: Flutter Format Validation

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - run: ls

      - run: echo ${{runner.tool_cache}}

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: '${{runner.tool_cache}}/flutter'
          key: '${{ runner.OS }}-flutter-sdk-cache-${{ env.flutter_version }}'

      # Setup Flutter SDK from Cache or cache new
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: stable
          cache: true
          cache-key: '${{ runner.OS }}-flutter-sdk-cache-${{ env.flutter_version }}'
          cache-path: '${{runner.tool_cache}}/flutter'
          architecture: x64

      - run: ls -la

      # Log Flutter version
      - name: Log Flutter version
        run: flutter --version

      # Download all Flutter packages
      - name: Download dependencies
        run: flutter pub get

      # Run Dart Format to ensure formatting is valid
      - name: Run Dart Format
        run: dart format -l 120 --set-exit-if-changed ./

      - name: Run Flutter Tests
        run: flutter test